# Generated by Django 6.0.5 on 2026-05-15 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_clientfile_approved_at_clientfile_approved_by_and_more'),
        ('documents', '0001_initial'),
        ('service_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='linked_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to='documents.generateddocument'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='linked_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to='clients.clientfile'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='linked_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to='clients.clientfolder'),
        ),
    ]
