# Generated by Django 6.0.5 on 2026-05-15 23:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0003_servicerequestactivity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='responded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilled_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='response_attachment',
            field=models.FileField(blank=True, null=True, upload_to='request_responses/'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='response_link',
            field=models.URLField(blank=True, max_length=700),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='response_message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='servicerequestactivity',
            name='action',
            field=models.CharField(choices=[('request_submitted', 'Request Submitted'), ('status_changed', 'Status Changed'), ('folder_linked', 'Folder Linked'), ('file_linked', 'File Linked'), ('document_linked', 'Document Linked'), ('comment_added', 'Comment Added'), ('assigned_to_staff', 'Assigned To Staff'), ('request_approved', 'Request Approved'), ('request_rejected', 'Request Rejected'), ('request_completed', 'Request Completed'), ('request_fulfilled', 'Request Fulfilled'), ('response_uploaded', 'Response Uploaded'), ('response_link_added', 'Response Link Added'), ('request_updated', 'Request Updated')], max_length=100),
        ),
    ]
