# Generated by Django 6.0.5 on 2026-05-15 23:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0004_servicerequest_responded_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='responded_at',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='responded_by',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='response_attachment',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='response_link',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='response_message',
        ),
        migrations.AlterField(
            model_name='servicerequestactivity',
            name='action',
            field=models.CharField(choices=[('request_submitted', 'Request Submitted'), ('status_changed', 'Status Changed'), ('folder_linked', 'Folder Linked'), ('file_linked', 'File Linked'), ('document_linked', 'Document Linked'), ('comment_added', 'Comment Added'), ('assigned_to_staff', 'Assigned To Staff'), ('request_approved', 'Request Approved'), ('request_rejected', 'Request Rejected'), ('request_completed', 'Request Completed'), ('request_fulfilled', 'Request Fulfilled'), ('response_uploaded', 'Response Uploaded'), ('response_link_added', 'Response Link Added'), ('response_downloaded', 'Response Downloaded'), ('request_updated', 'Request Updated')], max_length=100),
        ),
        migrations.CreateModel(
            name='ServiceRequestResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_message', models.TextField(blank=True)),
                ('response_attachment', models.FileField(blank=True, null=True, upload_to='request_responses/')),
                ('response_link', models.URLField(blank=True, max_length=700)),
                ('responded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('last_downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_downloaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downloaded_request_responses', to=settings.AUTH_USER_MODEL)),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_responses', to=settings.AUTH_USER_MODEL)),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='service_requests.servicerequest')),
            ],
        ),
    ]
