# Generated by Django 6.0.5 on 2026-05-16 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0005_remove_servicerequest_responded_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequestresponse',
            name='confirmation_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='servicerequestresponse',
            name='confirmation_status',
            field=models.CharField(choices=[('pending', 'Pending Confirmation'), ('accepted', 'Accepted'), ('changes_requested', 'Changes Requested')], default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='servicerequestresponse',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequestresponse',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_request_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servicerequestactivity',
            name='action',
            field=models.CharField(choices=[('request_submitted', 'Request Submitted'), ('status_changed', 'Status Changed'), ('folder_linked', 'Folder Linked'), ('file_linked', 'File Linked'), ('document_linked', 'Document Linked'), ('comment_added', 'Comment Added'), ('assigned_to_staff', 'Assigned To Staff'), ('request_approved', 'Request Approved'), ('request_rejected', 'Request Rejected'), ('request_completed', 'Request Completed'), ('request_fulfilled', 'Request Fulfilled'), ('response_uploaded', 'Response Uploaded'), ('response_link_added', 'Response Link Added'), ('response_downloaded', 'Response Downloaded'), ('response_accepted', 'Response Accepted'), ('response_changes_requested', 'Response Changes Requested'), ('request_updated', 'Request Updated')], max_length=100),
        ),
    ]
