# Generated by Django 6.0.5 on 2026-05-15 13:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('client_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('folder_path', models.CharField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ClientFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subfolder', models.CharField(choices=[('contracts', 'Contracts'), ('invoices', 'Invoices'), ('quotations', 'Quotations'), ('proposals', 'Proposals'), ('reports', 'Reports'), ('certificates', 'Certificates'), ('general', 'General')], default='general', max_length=50)),
                ('uploaded_file', models.FileField(upload_to='client_uploads/')),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('client_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='clients.clientfolder')),
            ],
        ),
    ]
