from django.contrib.auth import get_user_model
from django.core.management.base import BaseCommand
from django.core.files.base import ContentFile

from clients.models import ClientFolder
from clients.models import ClientFile
from clients.folder_tools import create_client_folder_structure

from documents.models import GeneratedDocument
from documents.pdf_generator import generate_business_pdf

from dashboard.activity import log_activity


class Command(BaseCommand):
    help = 'Creates demo data for That Corporate Flow.'

    def handle(self, *args, **options):
        User = get_user_model()

        demo_user, created_user = User.objects.get_or_create(
            username='demo_client',
            defaults={
                'email': 'demo@thatcorporateflow.com',
                'role': 'client',
                'company_name': 'Demo Client Company',
            }
        )

        if created_user:
            demo_user.set_password('DemoClient123!')
            demo_user.save()

        demo_clients = [
            ('Mtimkulu Consulting', 'admin@mtimkuluconsulting.co.za'),
            ('Alpha Poultry', 'ops@alphapoultry.co.za'),
            ('Nexa Cleaning Services', 'hello@nexacleaning.co.za'),
        ]

        for name, email in demo_clients:
            folder, created = ClientFolder.objects.get_or_create(
                client_name=name,
                defaults={
                    'owner': demo_user,
                    'client_email': email,
                    'folder_path': create_client_folder_structure(name),
                    'notes': 'Demo client folder.'
                }
            )

            if folder.owner is None:
                folder.owner = demo_user
                folder.save()

            if created:
                log_activity(
                    'folder_created',
                    f'Demo folder created: {name}',
                    'Generated by demo data script.'
                )

            demo_file, file_created = ClientFile.objects.get_or_create(
                client_folder=folder,
                title='Demo Service Agreement',
                defaults={
                    'subfolder': 'contracts',
                }
            )

            if file_created:
                safe_name = name.replace(' ', '_')

                demo_file.uploaded_file.save(
                    f'{safe_name}_agreement.txt',
                    ContentFile(f'Demo agreement file for {name}.'),
                    save=True
                )

                log_activity(
                    'file_uploaded',
                    f'Demo file uploaded: {name}',
                    'Generated by demo data script.'
                )

            document, doc_created = GeneratedDocument.objects.get_or_create(
                client_name=name,
                title='Demo Invoice',
                defaults={
                    'client_email': email,
                    'document_type': 'invoice',
                    'description': 'Demo invoice generated for Version 2 testing.',
                    'amount': 1500,
                }
            )

            if doc_created:
                pdf_path, filename = generate_business_pdf(document)
                document.file_path = pdf_path
                document.file_name = filename
                document.save()

                log_activity(
                    'document_generated',
                    f'Demo document generated: {name}',
                    'Generated by demo data script.'
                )

        self.stdout.write(
            self.style.SUCCESS('Demo data created successfully.')
        )

        self.stdout.write(
            self.style.SUCCESS('Demo client login: demo_client / DemoClient123!')
        )
