# Generated by Django 6.0.5 on 2026-05-15 13:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('folder_created', 'Folder Created'), ('folder_deleted', 'Folder Deleted'), ('file_uploaded', 'File Uploaded'), ('file_moved', 'File Moved'), ('file_archived', 'File Archived'), ('file_restored', 'File Restored'), ('file_deleted', 'File Deleted'), ('document_generated', 'Document Generated'), ('document_deleted', 'Document Deleted'), ('workflow_ran', 'Workflow Ran'), ('export_created', 'Export Created')], max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
