# Generated by Django 6.0.5 on 2026-05-17 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_internaltaskchecklistitem_tasktemplatechecklistitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolution_file', models.FileField(blank=True, null=True, upload_to='task_resolutions/')),
                ('resolution_link', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolutions', to='operations.internaltask')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
